### ISSUE TITLE
Build help

### ISSUE THREAD

**Issue by RobinMartinu** [NosCoreLegend/Launcher#24]
Hi, 
succesfully started the noscore login, world and master servers, but I seem unable to build this launcher. Could I ask for instructions please? Thanks

**Comment by 0Lucifer0** [comment]
You need yarn. this launcher is not working at the moment

**Comment by RobinMartinu** [comment]
Thank you very much, I have used another launcher and got into the game.
I ran into a problem though, with basically every interaction, i get "could not found handler implementation for packet with header glist, u_s, GM commands..."

Do I need other files to parse? I parsed the "parse for opennos all languages" as was mentioned in many tutorials.
Thanks for the fast answer

**Comment by 0Lucifer0** [comment]
NosCore is still in dev.

**Comment by RobinMartinu** [comment]
:( Wish I could help, but I think it's too difficult for me. Has opennos been abandoned due to unsolvable issues and is thus unplayable or is it just "stuck" at some older version?
I am looking for a singleplayer pvm experience and partly a coding challenge.

Well, sorry for bothering and thank you for your work, I hope that it will be functional some day.

**Comment by 0Lucifer0** [comment]
I just stopped opennos because it was not interested in it anymore. It’s opensource so everything is solvable.

**Comment by RobinMartinu** [comment]
Okay, thanks for your answers once again. Looking forward to NosCore!
